### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by FreshImmuc** [zmxhawrhbg/gdrpc#1]
Hey, I don't know much of Developing and Compiling and this stuff... and I want to install this. How do I do that? 

Greetings Immuc

**Comment by Altenhh** [comment]
You can find instructions on how to install this here: https://github.com/zmxhawrhbg/gdrpc#automatically.
as for the DLLs they are found

**Comment by zmxhawrhbg** [comment]
It has been almost a month and I haven't seen any further questions, I am going to lock this. Feel free to reopen it if anything occurs.
