### ISSUE TITLE
The User Experience isn't satisfactory

### ISSUE THREAD

**Issue by emiliosanches** [zmxhawrhbg/gdrpc#3]
Hey dude, have you forgot that the users aren't developers? You are forcing "normal" people to install git, vscode and use command-line interface. That's not close to be a good user experience.
You should let this repository so devs can learn and help you with the development and make your own and public Rich Presence, shared for all users, and release a compiled version of this project for Win x86, x64, and Linux using the application ID of your public Rich Presence.
As dev, you should think more about the users. Developing isn't just coding. You must think 'bout the requirements of your application, and it includes your users knowledge.
At least, add a prompt to ask for the application ID of the user if you don't want to develop your own Rich Presence.
This is your product, your project. It can reach thousands of people, and you are losing thousands of users because it is very complex to non-developers. Give your all for this and be proud of this.

**Comment by zmxhawrhbg** [comment]
:slightly_frowning_face:
